version: '3'
services:
  app:
    container_name: huddl
    image: ssastry22/atlas-repo:huddl
    ports: 
      - 8001:8001
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-postgres          
    networks:
      - fullstack
    environment:
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - DB_PORT
    
  fullstack-postgres:
    image: ssastry22/atlas-repo:psql
    container_name: postgres-db
    ports:
      - '5431:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack


volumes:
  api:
  database_postgres:  
  consumer:                

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
